import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar"
import { useFavState } from "@/stores/useFavStore"
import { usersTable } from '@/src/db/schema'
import { db } from '@/src/db'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    //const setFavList = useFavState((state) => { state.setFavList });
    //setFavList([""]);
    return (
        <html lang="en">
            <body>
                <Navbar></Navbar>
                {children}
                <div style={{ height: "1000px" }}></div>
            </body>
        </html>
    );
}
